// <auto-generated />
namespace EntityExtensions.Tests.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class level12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(level12));
        
        string IMigrationMetadata.Id
        {
            get { return "201712132110569_level1-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
