// <auto-generated />
namespace EntityExtensions.Tests.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class EmpManager : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmpManager));
        
        string IMigrationMetadata.Id
        {
            get { return "201711061146500_EmpManager"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
